### PR TITLE
Emotions task - cowengifs/horikawa design

### PR DESCRIPTION
**Pull request by sangfrois**
## Session script : 

`src/sessions/ses-emotions.py`

based on `ses-liris.py`, the script presents gifs in an order predefined in a `.csv`  file.

## Need help with : 
- repeating the gifs that are less than 8 seconds
- prompting fixation cross 
- prompting the subject with valence and arousal (could be on
both sides of the controller, arrows for arousal and buttons for valence)

### CODE REVIEW

**Comment by sangfrois** [comment]
@bpinsard I pushed parcimonious changes, if you have time to look it up it would be great

@pbellec couple of days late, but here it is. It's a start.

I'm putting this PR against master branch as I don't really know what the appropriate workflow. Tell me if I should create a new branch on courtois-neuromod

**Comment by bpinsard** [comment]
@sangfrois do you have a description of your design? how many sessions, how many runs, the timing within runs,... . I think that having a google-doc with a detailed design would help. Thanks!

**Comment by sangfrois** [comment]
Hi @bpinsard thank you for that.
I'll write the info here first so that you get the answer quickly: 

1.  8 sessions
2.  61 runs - 5 to 8 runs a session
3. 7 to 10 mins by runs
4.  Total duration : 8 hours

in order to get a .csv with the proper duration of each run/ses by subject (randomized order for GIFS), I would need some help. 

See a .csv with duration info for each gif in my PR. We would first need to save a repeated version of gifs that are under 8 (like Horikawa) or 6 seconds (so that it is divisble by our TR period). I figured you probably knew some python trick to repeat a video.  Am I mistaken ? Tell me if I am, cause I will have a look into that ASAP if you don't know any trick

**Comment by bpinsard** [comment]
From the script you wrote, you are presenting each clip in a separate "task" (with each waiting for a TTL, etc..,) I think it will instead require to write a new task to show multiple clips per run, and specify what is the ISI). 
Then we can write a script to pre-generated tsv events files with different pseudo-randomization per participant. You will likely want to balance the clips categories, valence, ....  across runs, sessions.... It would be great to have a clear description of these design details and have inputs from Pierre R, @pbellec @julieaboyle1.

**Comment by sangfrois** [comment]
I understand where you are getting at.

I will try to cover a new task file to load a block of stimuli for a run and the next days. I already gave it some thought, and figured we'd want to build a video of multiple gifs for a given run/participants.

I totally agree that we need to think of balancing gifs by ratings. I discussed this with PierreR extensively. But after exchanging with @pbellec recently, we agreed that there is added value on replicating designs as is. So I went ahead and based this PR on Horikawa's [supplemental info paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7191651/#)

**Comment by bpinsard** [comment]
Ok, I was missing this infos.
From their design:
-  I don't understand why the rest period is longer at the beginning than at the end, the latter is only 6 sec, so not long enough for the HRF to vanish, while the 32s at the beginning is way too long for the participant. 
- They do no describe how it was randomized. One option would be to take the events files for the 5 participants they ran, and adapt the timing to our TR. However it would be better to have conditions to be well balanced, if we could have some stats on their design, that would be ideal.
- As the length of a run depends on the length of the individual videos, they do not have fixed length, and it will vary depending on each participant's randomization. This will require a lot of manual operation at the console, which is time-consuming and error-prone. If possible we would try to match the duration across runs/participants/sessions  by either having a different number of clips per run, or randomization taking into account the duration  ( the rest period can be slightly extended to round the duration if necessary) .

**Comment by sangfrois** [comment]
Alright. 
I'll push some stats this branch. I have a notebook on that already.

You could be right, I assumed they had randomized blindly, but maybe they did not.

I'll let you know about that ASAP

**Pull request closed without merging**
